In [17]:
# Exempeluppgifter

In [18]:
#Basic recursive function that returns the sum of all the number leading up to the number given as an argument
def sum(n): 
	if n == 1:
		return 1      #Base case
	else: 
		return n + sum(n-1)   #Recursive call

test = sum(4)
print(test)

#Reverse a string with recursion
def reverse_string(string):
	if len(string) == 1:     #Base case
		return string
	else:
		return reverse_string(string[1:]) + string[0]   #Recursion
	
test = reverse_string("Cykel")
print(test)

#Hanois tower with recursion
def hanoi(N, A, B, C):
	if N == 1:
		print(f"Move from {A} to {C}.")     #Base case
	else:
		hanoi(N-1, A, C, B)     #Recursion
		print(f"Move from {A} to {C}")      
		hanoi(N-1, B, A, C)
		
test = hanoi(3, "A", "B", "C")

10
lekyC
Move from A to C.
Move from A to B
Move from C to B.
Move from A to C
Move from B to A.
Move from B to C
Move from A to C.


In [19]:
#Simple class
class Coordinate(object):   #Definition, the class inherits from the object class. 
	def __init__(self, x, y):      #Constructor of the object in the class.
		self.x = x
		self.y = y
	def distance(self, other):      #Method for the objects in the class, in this case we calculate the distance between two points. 
		x_diff_sq = (self.x - other.x)**2
		y_diff_sq = (self.y - other.y)**2
		return (x_diff_sq + y_diff_sq)**0.5
	def __str__(self):      #String function that lets you print the objects in a desired way. 
		return "("+str(self.x)+", "+str(self.y)+")"

a = Coordinate(1, 2)    #Creating an intance (object) of the defined class
b = Coordinate(3, 4)
print(a.distance(b))    #Calculating the ditance to another point with the method we defined. 
print(a)       #Printing the object "a"

2.8284271247461903
(1, 2)


In [20]:
#Mutable object
myLst = [1, 2, 3]
myNewLst = myLst
myNewLst.append(4)
print(myLst, myNewLst)

[1, 2, 3, 4] [1, 2, 3, 4]


In [21]:
#Lab 2 -part 1 and 2 toghether. 

class Employee:
    def __init__(self, name, employee_id, email, position, salary):
        self.name = name
        self.employee_id = employee_id
        self.email = email
        self.position = position
        self.salary = salary
        self.earnings = []
        self.manager = None

    def get_details(self):
        return f"Name: {self.name}, employee_id: {self.employee_id}, email: {self.email}, position: {self.position}, salary: {self.salary}"
   
    def salary_raise(self, percent):
        print(f"Increased {self.name}'s salary by {percent}%.")
        percent = (percent / 100) + 1
        self.salary *= percent

    def calculate_bonus(self):
        bonus = self.salary * 0.05
        return bonus
    
    def make_sale(self, inventory, item, amount):
        sale = inventory.remove_item(item, amount)
        if sale is not None:
            print(f"{self.name} sold {amount} {item.name}s to the price of {item.price} each.")
            self.earnings.append(sale.price * amount)

class Manager(Employee):
    def __init__(self, name, employee_id, email, position, salary):
        super().__init__(name, employee_id, email, position, salary)
        self.subordinates = []
        self.subordinates_sales = []
        self.manager = None

    def add_subordinate(self, employee):
        if employee in self.subordinates:
            return
        else: 
            self.subordinates.append(employee)
            employee.manager = self

    def remove_subordinate(self, subordinate_to_remove):
        if subordinate_to_remove in self.subordinates:
            self.subordinates.remove(subordinate_to_remove)
            subordinate_to_remove.manager = None
        else:
            return

    def get_subordinates(self):
        print(f"{self.name}'s Subordinates:")
        for employee in self.subordinates:
            print(employee.get_details())

    def get_subordinates_sales(self):
        total_sum = sum(sum(subordinate.earnings) for subordinate in self.subordinates)
        print(f"The total earnings of {self.name}'s subordinates is {total_sum}.")

    def calculate_bonus(self):
        subordinates_salaries = 0
        for subordinate in self.subordinates:
            subordinates_salaries += subordinate.salary
        manager_bonus = super().calculate_bonus() + (subordinates_salaries * 0.01)
        return manager_bonus
    
class Company:
    def __init__(self, name, general_manager):
        self.name = name
        self.employees = [general_manager] #Adding the general manager to the list of employees imidiatly. 
        self.general_manager = general_manager #Adding the attribute general manager
        
    def add_employee(self, employee, manager_id):
        try:    # I use a try except block to rule the exception that is raised when an instnce of manager is added to an instance om employee. 
            stack = [self.general_manager]  #Creating the stack for the DFS. 
            while stack:    #Creating a while loop that will itterate as long as the stack is not empty. 
                current_manager = stack.pop()  #selecting the manager for the current itteration of the while loop by popping the first item from the stack. 
                if current_manager.employee_id == manager_id:   #Checking if the selected manager is the one we are looking for. If so:
                    current_manager.add_subordinate(employee)   #We call the add_subordinate method from the manager class to set the employee as a subordinate to the manager.
                    print(f"Added {employee.name} to {current_manager.name}'s team.")
                    self.employees.append(employee)   #Adding the employee to the list of employees of employees 
                    return
                stack.extend(reversed(current_manager.subordinates))      #If the manager was not found, we add the list of subordinates of the current manager to the stack in reversed order (so that the last subordinate is processed first) and begin a new itteration. This creates the depth first loop.
            print(f"Manager with ID {manager_id} not found in the company.")
        except AttributeError:      # If an exception is raised it is becasue we tried to add a manager to an employee.
            print("ERROR: Employees must be added to managers.")

    def remove_employee(self, employee):
        if employee in self.employees:      # Checking if the employee is in the list of employees.
            print(f"Fired {employee.name} from {self.name}.") 
            if isinstance(employee, Manager):   #Checking if the employee we want to remove is a manager. If the employee is only an employee, we jump to removing the employee from the company and from the employees managers list of subordinates. 
                if employee.manager:    #If it is a manager we want to remove, we check if that manager also have a manager. 
                    for subordinate in employee.subordinates:       #If the manager has a manager, we loop through the subordinates of the manager to be removed. 
                        employee.manager.add_subordinate(subordinate)       #For each subordinate of the manager we want to remove, we use the add_subordinate method to add the subordinates of the manager to its manager. 
                    print(f"Transferred {employee.name}'s subordinates to {employee.manager.name}.")
                else:
                    print(f"No manager found for {employee.name}. Subordinates not transferred.")   #If the manager we want to remove does not have a manager, we print that we can not transfer the managers subordinates. 
            self.employees.remove(employee)        #Deleting the employee from the companys list of employees
            employee.manager.subordinates.remove(employee)      #Deleting the employee from its managers list of employees. 
        else:
            print(f"{employee.name} is not an employee under {self.name}.")     #If the employee we want to remove is not in the list of employees, we print this information and do nothing else. 

    def list_employees(self):
        n = 0   #Counter for the ammount of employees in the company.
        print(f"{self.name}'s employees:")      #printing a headline
        visited = set()     # Creating a set to store the visited nodes in the tree of employees in the company so that we do not 
        queue = [self.general_manager]      #Creating a queue for the BFS.
        while queue:    #While the queue has employees in it, we itterate with a while loop. 
            current_employee = queue.pop(0)     #Selecting the employee for this itteration of the while loop by taking the first item from the queue.
            if current_employee not in visited:     #If the selected employee has not been visited, we continue. If the employee of this itteration is in the visited set, it means that we already covered this employee. 
                print(current_employee.get_details())   #Getting the details of the selected employee by using the get_details method from the employee class. 
                visited.add(current_employee)       #Adding the selected employee to the set of visited employees so that we do not visit it again. 
                if isinstance(current_employee, Manager):       #Checking if the current employee is a manager, if so: 
                    queue.extend(current_employee.subordinates)     #We add the managers subordinates to the queue. This will ensure that the next itteration will be tha subordinates of the
                n += 1  #Adding a number to the counter that is later going to be printed. 
        print(f"Total number of employees is {n}.") 

    def calculate_company_salary(self):
        total_salary = 0
        for employee in self.employees.values():
            if employee is not None:
                total_salary += employee.salary
        total_salary += self.general_manager.salary
        print(f"The total salary of {self.name} is {total_salary}.")
    
class Item:
    def __init__(self, name, price):
        self.name = name
        self.price = price

    def __str__(self):
        return f"Name:{self.name}, Price:{self.price}"

class Inventory:
    def __init__(self):
        self.inventory = []

    def add_item(self, item, amount=1):
        in_inventory = False
        for articles in self.inventory:
            if articles["Item"].name == item.name and articles["Item"].price == item.price:
                articles["Amount"] += amount
                in_inventory = True
                break
        if not in_inventory:
            self.inventory.append({"Item": item, "Amount": amount})

    def remove_item(self, item, amount=1):
        in_inventory = False
        for articles in self.inventory:
            if articles["Item"].name == item.name and articles["Item"].price == item.price:
                if articles["Amount"] - amount < 0:
                    print(f"Amount of {item.name}s to the price of {item.price} to remove exceeds amount in inventory.")
                    return None
                else:
                    articles["Amount"] -= amount
                    if articles["Amount"] == 0:
                        self.inventory.remove(articles)
                    return item
        print(f"Product is not in inventory.")
        return None

    def display_inventory(self):
        print(f"Current inventory is:")
        for item in self.inventory:
            print(f" - {item['Amount']} {item['Item'].name}s to a price of {item['Item'].price} per {item['Item'].name}")

class Client:
    def __init__(self, name, company_name, company_location):
        self.name = name
        self.company_name = company_name
        self.company_location = company_location
    
class Meeting_planner:
    def __init__(self):
        self.booked_meetings = []

    def book_meeting(self, employee, client, date, time):
        print(f"{employee.name} booked a meeting with {client.name} at {client.company_name} in {client.company_location}. The date is {date} and the time is {time}.")
        meeting = {"Employee": employee.name, "Client": client.name, "Date": date, "Time": time}
        self.booked_meetings.append(meeting)

    def remove_meeting(self, employee, client, date, time):
        booked_meeting = False
        for meetings in self.booked_meetings:
            if meetings["Employee"] == employee.name and meetings["Client"] == client.name and meetings["Date"] == date and meetings["Time"] == time:
                self.booked_meetings.remove(meetings)
                print(f"Removed meeting with {client.name} on the given date and time.")
                booked_meeting = True
                break
        if not booked_meeting:
            print(f"There is no meeting between {employee.name} and {client.name} on the given date and time.")

    def reschedule_meeting(self, employee, client, old_date, old_time, new_date, new_time):
        booked_meeting = False
        for meetings in self.booked_meetings:
            if meetings["Employee"] == employee.name and meetings["Client"] == client.name and meetings["Date"] == old_date and meetings["Time"] == old_time:
                meetings["Date"] = new_date
                meetings["Time"] = new_time
                print(f"Rescheduled meeting with {client.name} to the date {new_date} and time {new_time}.")
                booked_meeting = True
                break
        if not booked_meeting:
            print(f"There is no meeting between {employee.name} and {client.name} on the given date and time.")

    def show_booked_meetings(self):
        print(f"Booked meetings:")
        for meeting in self.booked_meetings:
            print(f"Employee: {meeting['Employee']}, Client: {meeting['Client']}, Date: {meeting['Date']}, Time: {meeting['Time']}.")

ceo1 = Manager("Emma", 1, "name@company.com", "CEO", 35000)

man2 = Manager("Amanda", 2, "name@company.com", "Manager", 35000)
man3 = Manager("Erik", 3, "name@company.com", "Manager", 35000)

man4 = Manager("Adrian", 4, "name@company.com", "Manager", 35000)
man5 = Manager("Alma", 4, "name@company.com", "Manager", 35000)

emp6 = Employee("Adam", 6, "name@company.com", "sales", 35000)
emp7 = Employee("Nicholas", 7, "name@company.com", "sales", 35000)
emp8 = Employee("Victor", 8, "name@company.com", "sales", 35000)
emp9 = Employee("Elizabete", 9, "name@company.com", "sales", 35000)
emp10 = Employee("Norea", 10, "name@company.com", "sales", 35000)
emp11 = Employee("Jacob", 11, "name@company.com", "sales", 35000)

company1 = Company("ABC Company", ceo1)

print()
company1.add_employee(man2, ceo1.employee_id)
company1.add_employee(man3, ceo1.employee_id)
company1.add_employee(man4, man2.employee_id)
company1.add_employee(man5, man3.employee_id)
company1.add_employee(emp6, man4.employee_id)
company1.add_employee(emp7, man4.employee_id)
company1.add_employee(emp8, man4.employee_id)
company1.add_employee(emp9, man5.employee_id)
company1.add_employee(emp10, man5.employee_id)
company1.add_employee(emp11, man5.employee_id)

print()
company1.list_employees()
print()
company1.remove_employee(man3)
company1.remove_employee(emp7)
company1.remove_employee(man3)
company1.remove_employee(man4)
company1.remove_employee(emp11)
company1.add_employee(man2.employee_id, emp7)
print()
company1.list_employees()
print()
man2.get_subordinates()
print()

item1 = Item("car", 10000)
item2 = Item("boat", 25000)
item3 = Item("plane", 100000)
item4 = Item("train", 50000)
item5 = Item("car", 15000)

inventory1 = Inventory()
inventory1.add_item(item1, 5)
inventory1.add_item(item2, 3)
inventory1.add_item(item3, 4)
inventory1.add_item(item4)
inventory1.add_item(item5)

print()
inventory1.display_inventory()

print()
client1 = Client("Norea", "ABC Transportation Company", "Halmstad")
meetings = Meeting_planner()

meetings.book_meeting(emp8, client1, "25/11", "13:00")
print()
meetings.reschedule_meeting(emp8, client1, "25/11", "13:00", "1/12", "14:00")
print()
meetings.show_booked_meetings()
print()
emp8.make_sale(inventory1, item3, 4)
print()
man2.get_subordinates_sales()
print()
inventory1.display_inventory()
print()
meetings.remove_meeting(emp8, client1, "1/12", "14:00")



Added Amanda to Emma's team.
Added Erik to Emma's team.
Added Adrian to Amanda's team.
Added Alma to Erik's team.
Added Adam to Adrian's team.
Added Nicholas to Adrian's team.
Added Victor to Adrian's team.
Added Elizabete to Adrian's team.
Added Norea to Adrian's team.
Added Jacob to Adrian's team.

ABC Company's employees:
Name: Emma, employee_id: 1, email: name@company.com, position: CEO, salary: 35000
Name: Amanda, employee_id: 2, email: name@company.com, position: Manager, salary: 35000
Name: Erik, employee_id: 3, email: name@company.com, position: Manager, salary: 35000
Name: Adrian, employee_id: 4, email: name@company.com, position: Manager, salary: 35000
Name: Alma, employee_id: 4, email: name@company.com, position: Manager, salary: 35000
Name: Adam, employee_id: 6, email: name@company.com, position: sales, salary: 35000
Name: Nicholas, employee_id: 7, email: name@company.com, position: sales, salary: 35000
Name: Victor, employee_id: 8, email: name@company.com, position: sales

TypeError: unsupported operand type(s) for -: 'generator' and 'int'

In [ ]:
myVar = 5 
otherVar = "aaa"
print("myVar = 7") 
print("myVar =", myVar)
print(otherVar, "bbb", otherVar + "ccc", "otherVar" + "ccc") 
thirdVariable = myVar + 1 + otherVariable


myVar = 7
myVar = 5
aaa bbb aaaccc otherVarccc


NameError: name 'otherVariable' is not defined

In [ ]:
def to_seconds(hours, minutes):
    hours_to_seconds = hours * 60 * 60
    minutes_to_seconds = minutes * 60
    return hours_to_seconds + minutes_to_seconds

hours = 2
minutes = 11

seconds = to_seconds(hours, minutes)
print(seconds)

    

7860


In [ ]:
newVar = [1,2,3]
def myFunction(arg = 5): 
    print(newVar) 
    newVar.append(arg)
myFunction() 
newVar[0] = -1 
myFunction(7) 
newVar[1] = -5 
myFunction(9)
print(newVar)


[1, 2, 3]
[-1, 2, 3, 5]
[-1, -5, 3, 5, 7]
[-1, -5, 3, 5, 7, 9]


In [ ]:
a, b, c = 1, 2, 3
if a < b:
    print("I’m thinking") 
    if b < c:
        print("a is largest")
    else:
        print("b is largest")
 
    print("I don’t know") 
    if a > 0:
        print("Positive")
    else:
        print("I’m really confused")
    print(a, b, c)


I’m thinking
a is largest
I don’t know
Positive
1 2 3


In [ ]:
def MinorityVote(list):  #title is wrong
    counter = {}
    while elem in list:     #This will run forever since we do not remove anything from the list. W should use a for loop instead. 
        counter.elem += 1   #.elem does not do anything. We need to create a key for each unique item and then counting how many of the same there are in the list
    half = len(list) * 2    #We should be dividing by 2, no multiplying
    for elem in counter:    #
        if counter[elem] >= half:   #For it to be the majority, it can not be equal to half. Also, we need to compare the corresponding value of the key. 
            return counter  #
    return counter[0]   #We never want to return this, if there is no majority, we should return something to indicate this. 


def Majority_vote(lst):  
    counter = {}
    for elem in lst: 
        if elem in counter:
            counter[elem] += 1
        else:
            counter[elem] = 1
    half = len(lst) // 2 
    for elem, count in counter.items():
        if count > half: 
            return elem
    return "there is no majority"


lst = [2,2,2,2,1,3,4,4,4,4,4,4,4]
result = Majority_vote(lst)
print(result)



4


In [23]:
def selectNegative(lst):
    new_lst = []
    for elem in lst:
        if elem <= 0:
            new_lst.append(elem)
        else:
            continue
    return new_lst

list = [1, 2, -5, 3, -7, 0, -1, 1]
rsult = selectNegative(list)
print(rsult)

[-5, -7, 0, -1]


In [3]:
def odd_indexes(list):
    new_lst = []
    index = 0
    for elem in list:
        if index % 2 != 0:
            new_lst.append(elem)
        index += 1
    return new_lst
        

lst = [1,2,3,4,5]
res = odd_indexes(lst)
print(res)

[2, 4]


In [9]:
mystring = "abcd"
letter_idx = 0
while letter_idx != len(mystring):
    print(mystring[letter_idx].upper())
    letter_idx += 1



A
B
C
D


In [10]:
def findLast(letter, word_list):
    last_matching_word = None

    for word in word_list:
        if letter in word:
            last_matching_word = word

    return last_matching_word

# Example usage:
result1 = findLast('a', ['abc', 'bcd', 'xyz', 'zzz'])
result2 = findLast('a', ['abc', 'bcd', 'aaa', 'bbb'])

print(result1)  # Output: "abc"
print(result2)  # Output: "aaa"


abc
aaa


In [12]:



letters = 'abcdefghijklmnopqrstuvwxyz'

def atbash(text):
    result = ""
    
    for letter in text:
        if letter.islower():
            index = letters.index(letter)
            code = letters[25 - index]  # Mirroring the index
        elif letter.isupper():
            index = letters.index(letter.lower())
            code = letters[25 - index].upper()  # Mirroring the index and converting to uppercase
        else:
            code = letter  # If the character is not a letter, keep it unchanged
        
        result += code
    
    return result

# Example usage:
input_text = "Hello, World!"
encrypted_text = atbash(input_text)
print(f"Original text: {input_text}")
print(f"Encrypted text: {encrypted_text}")


Original text: Hello, World!
Encrypted text: Svool, Dliow!


In [21]:
def morse(text):
    result = ""
    char_to_dots = {'A': '.-', 'B': '-...', 'C': '-.-.', 'D': '-..', 'E': '.', 'F': '..-.', 'G': '--.', 'H': '....',
                'I': '..', 'J': '.---', 'K': '-.-', 'L': '.-..', 'M': '--', 'N': '-.', 'O': '---', 'P': '.--.',
                'Q': '--.-', 'R': '.-.', 'S': '...', 'T': '-', 'U': '..-', 'V': '...-', 'W': '.--', 'X': '-..-',
                'Y': '-.--', 'Z': '--..'}
    for letter in text:
        if letter in char_to_dots:
            code = char_to_dots[letter]
            result += " " + code
        else:
            continue
    return result
    

# Example usage:
input_text = "HEJSAN SVENJSAN BANANPANKAKA"
morse_code = morse(input_text)
print(f"{input_text} encoded in Morse code: {morse_code}")

HEJSAN SVENJSAN BANANPANKAKA encoded in Morse code: .... . .--- ... .- -. ... ...- . -. .--- ... .- -. -... .- -. .- -. .--. .- -. -.- .- -.- .-


In [ ]:
myList = [1,2,3,4]
def myFunction(lst):
    lst.append(0)
    print(lst)
print(myList)

In [5]:
a = 5
def myFunc():
    return a + 1

aa = myFunc()

bb = myFunc

print(aa)
print(bb())

6
6


In [6]:
for var in "abcdef":
    if var not in "aeoui":
        var = var.upper()

In [8]:
myList = [1,2,3,4] 
otherList = myList
thirdList = otherList.copy() 
myList[0] = 100
print(myList, otherList, thirdList)


[100, 2, 3, 4] [100, 2, 3, 4] [1, 2, 3, 4]


In [19]:
def power(n, k):
    if k == 0:
        return 1
    else:
        return power(n, k-1) *n

print(power(5, 2))

25


In [27]:
def sum_list(list, num_elements):
    if num_elements == 1:
        return list[num_elements-1]
    else:
        return list[num_elements-1] + sum_list(list, num_elements-1)

test = [5,5,5,5]
print(sum_list(test, 4))

20


In [29]:
def get_permutations(lst):
    if len(lst) == 0:
        return[[]]  #the only permutation of a list with len=0 is an empty list
    else:
        all_perms = []  
        for i in range(len(lst)):
            current_element = lst[i]
            rest_of_elements = lst[:i] + lst[i+1:]
            rest_permutations = get_permutations(rest_of_elements)
            for perm in rest_permutations:
                all_perms.append([current_element] + perm)
        return all_perms
    
test = ["a","b","c"]
print(get_permutations(test))

[['a', 'b', 'c'], ['a', 'c', 'b'], ['b', 'a', 'c'], ['b', 'c', 'a'], ['c', 'a', 'b'], ['c', 'b', 'a']]


In [38]:
import numpy as np

values = []
for _ in range(6):
    values.append([1,2,3,4,5,6])
arr = np.array(values)
arr.shape
print(arr)
print(np.sum(arr))
print(np.sum(arr, axis=1))
print(np.sum(arr, axis=0))

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]
 [1 2 3 4 5 6]]
126
[21 21 21 21 21 21]
[ 6 12 18 24 30 36]


In [63]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import altair as alt

data = pd.read_csv(r"iris.csv")
print(data.shape)
print(data.columns)
print(data[["sepal_length", "sepal_width"]])    #double brackets when printing multiple classes
print(data.mean(axis=0))
print(data[data["sepal_width"] > 5])

arr = np.array(data)



(100, 5)
Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class'], dtype='object')
    sepal_length  sepal_width
0       0.583333     0.333333
1       0.388889     0.750000
2       0.861111     0.333333
3       0.916667     0.416667
4       0.833333     0.375000
..           ...          ...
95      0.472222     0.083333
96      0.416667     0.291667
97      0.083333     0.666667
98      0.666667     0.458333
99      0.222222     0.541667

[100 rows x 2 columns]
sepal_length    0.424167
sepal_width     0.431250
petal_length    0.464746
petal_width     0.455833
dtype: float64
Empty DataFrame
Columns: [sepal_length, sepal_width, petal_length, petal_width, class]
Index: []


C:\Users\victo\AppData\Local\Temp\ipykernel_20432\4181426017.py:6: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(data.mean(axis=0))
